spring.application.name=backend

spring.datasource.url=jdbc:postgresql://terraform-8a400ce3fc73ac5b560e932c92.c4hkpkakfuj6.us-east-1.rds.amazonaws.com:5432/solicitudes_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update

# Permite que el backend valide el JWT, su firma, issuer y vigencia automáticamente
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_QFG6OPNPb