spring.application.name=backend

# Conexión a RDS PostgreSQL en AWS
spring.datasource.url=jdbc:postgresql://terraform-f97030dda07cd209fc724abcaf.chsjn5jmislw.us-east-1.rds.amazonaws.com:5432/solicitudes_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# Cognito Issuer URI
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_oMGJ7BEEu

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect